config/routes.rb
Rails.application.routes.draw do
  resources :posts, path: 'read'

  root to: 'visitors#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.limit(100)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_signed_in?
    false
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav id="welcome-nav" class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a class="" href="/">after school</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li><a href="/about">about</a></li>
      <li><a href="/projects">projects</a></li>
      <li><a href="/blog">blog</a></li>
      <li><a href="/feed.xml">feed</a></li>
    </ul>
  </section>
</nav>
<div id="zen">
  <div class="row">
    <div class="enlightenment large-12 columns">
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= title %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "School" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="row">
      <main id="main" role="main" class="large-12 small-12 columns">
        <%= yield %>
      </main>
      <section id="sidebar" role="sidebar" class="large-12 small-12 columns">
      </section>
    </div>
    <div class="row">
      <footer>
        <section class="large-12 columns center-inline-list">
          <ul>
            <li><%= link_to 'Archives', posts_path %></li>
          </ul>
        </section>
      </footer>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the School</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/posts/index.html.erb
<ul>
  <% @posts.each do |post| -%>
    <li>
      <%= link_to post.title, post %>
    </li>
  <% end -%>
</ul>

app/views/visitors/index.html.erb
<h3>Welcome</h3>